### ISSUE TITLE
Installation dies requiring sdl2

### ISSUE THREAD

**Issue by marhar** [felixangell/strife#8]
sdl2 is not mentioned in the quick start.  What should be installed for this prerequisite?

    ~ $ go get github.com/felixangell/strife
    # pkg-config --cflags sdl2
    Package sdl2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sdl2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'sdl2' found
    pkg-config: exit status 1

**Comment by felixangell** [comment]
I only list the Mac OS install instructions on the README:

```
$ brew install SDL2 SDL2_ttf SDL2_img
```

You would need sdl2, sdl-ttf, sdl2-img. What OS are you trying to build on? If you're building on Windows, it's a bit of a pain which is something I want to try and improve in the future.
